sudo: required
language: java

services:
  - docker

jdk:
  - oraclejdk8

env:
  global:
    - DOCKER_CFG=$HOME/.docker
    - DOCKER_REPO="utplsqlv3/oracledb"
    - CACHE_DIR=$HOME/.cache
    - MAVEN_HOME=/usr/local/maven
    - MAVEN_CFG=$HOME/.m2
    - DB_URL="127.0.0.1:1521:XE"
    - DB_USER=app
    - DB_PASS=app
    - ORACLE_VERSION="11g-r2-xe"
    - DOCKER_OPTIONS="--shm-size=1g"

cache:
  directories:
    - $DOCKER_CFG
    - $CACHE_DIR
    - $MAVEN_CFG

install:
  - bash .travis/maven_cfg.sh
  - bash .travis/start_db.sh
  - bash .travis/install_utplsql.sh
  - bash .travis/install_demo_project.sh

script:
  - mvn package 

#before_deploy:
#  - bash .travis/create_release.sh
#  - if [ ! -z "$TRAVIS_TAG" ]; then VERSION=$(tr -d "/v/" <<<$TRAVIS_TAG); mvn org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=${VERSION}; fi
#
#deploy:
#  - provider: releases
#    api_key: $GITHUB_API_TOKEN
#    file: utPLSQL-cli.zip
#    skip_cleanup: true
#    on:
#      repository: utPLSQL/utPLSQL-cli
#      tags: true
#  - provider: bintray
#    file: bintray.json
#    user: ${BINTRAY_USER}
#    key: ${BINTRAY_API_KEY}
#    dry-run: false
#    skip_cleanup: true
#    on:
#      repository: utPLSQL/utPLSQL-cli
#      branch: develop
#
